name: Python tests

on:
  push:
    branches: [ Github-Actions-1 ]
  pull_request:
    branches: [ Github-Actions-1 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip --upgrade pipenv wheel
          pip install numpy
          pip install -r requirements.txt
      - name: Update
        run: sudo apt-get update   
      - name: Prerequisites
        run: sudo apt-get install build-essential libmpfr-dev libgmp-dev libmpc-dev texinfo libncurses5-dev bison flex
      - name: Install pru-gcc dependencies
        run: sudo apt-get install -y gcc-pru gnuprumcu
      - name: "Create build directory and run CMake"
        run: cmake -S . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
      - name: "Build Project" 
        run: cmake --build build --target all --config Release -- -j4 
      - name: Execute py script
        run: python test.py
