name: Python tests

on:
  push:
    branches: [ Github-Actions-1 ]
  pull_request:
    branches: [ Github-Actions-1 ]
    
jobs:
    build_simppru_job1:
        runs-on: ubuntu-latest
        name: This will build simppru on x86 machines
        steps: 
            - name: Checkout
              uses: actions/checkout@v2
            - name: preconfig
              run: sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            - name: build inside docker amd64
              uses: ./.github/action_build_amd64
            - name: postconfig
              run: ls build -l


    build_simppru_job2:
        runs-on: ubuntu-latest
        name: This will build simppru on arm32 machine
        steps: 
            - name: Checkout
              uses: actions/checkout@v2
            - name: preconfig
              run: sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            - name: build inside docker arm32
              uses: ./.github/action_build_arm32
            - name: postconfig
              run: ls build -l
    test:
      runs-on: ubuntu-latest
      needs: [build_simppru_job1,build_simppru_job2 ]
  
      steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip --upgrade pipenv wheel
          pip install numpy
          pip install -r requirements.txt
     
      - name: Execute py script
        run: python test.py
